[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt" }

[[language]]
name = "beancount"
auto-format = true
formatter = { command = "bean-format" } 

[[language]]
name = "lua"
auto-format = true
formatter = { command = "lua-format" }

[[language]]
name = "python"
auto-format = true
formatter = { command = "black", args = ["--quiet", "-"] }
